main: com.winthier.hopperfilter.HopperFilterPlugin
name: HopperFilter

version: 0.1
api-version: '1.20'

description: Turn hoppers into filters when item frames are attached
author: StarTux
website: https://github.com/StarTux/HopperFilter

depend: [Mytems]
softdepend: []

commands:

  hopperfilter:
    description: Admin interface
    usage: |-
      /hopperfilter debug - Toggle debug output.
      /hopperfilter inspect - Toggle inspection mode.
    permission: hopperfilter.hopperfilter

permissions:

  hopperfilter.hopperfilter:
    description: Use the /hopperfilter command.
    default: op
